source 'https://github.com/CocoaPods/Specs.git'
platform :ios,'9.0'
target 'easyVideo-iOS' do
inhibit_all_warnings!
pod 'CocoaLumberjack'
pod 'MJRefresh'
pod 'SDWebImage'
pod 'HQHUtils', '1.0.10'
pod 'IQKeyboardManager'
pod 'GCDMulticastDelegate'
pod 'MBProgressHUD'
pod 'WechatOpenSDK'
pod 'JPush'
pod 'CJBaseHelper/UIViewControllerCJHelper'
pod 'ZipArchive'
pod 'Masonry'
pod 'MJRefresh'
end
